
DROP TABLE IF EXISTS T_SALARY;
DROP TABLE IF EXISTS T_ADDRESSES;
DROP TABLE IF EXISTS T_MAILS;
DROP TABLE IF EXISTS T_PEOPLE;
DROP TABLE IF EXISTS T_TYPES;
DROP TABLE IF EXISTS hibernate_sequence;


CREATE TABLE hibernate_sequence
(
  next_val bigint
);

CREATE TABLE T_PEOPLE (
    ID bigint NOT NULL,
    FULL_NAME VARCHAR(90) NOT NULL,
    PIN VARCHAR(10),
    primary key (ID)
);

CREATE TABLE T_MAILS (
    ID bigint NOT NULL,
    T_PEOPLE_ID bigint NOT NULL references T_PEOPLE(ID) ON DELETE CASCADE,
    EMAIL_TYPE VARCHAR(5) NOT NULL,
    EMAIL VARCHAR(40),
    primary key (ID)
);

CREATE TABLE T_ADDRESSES (
    ID bigint NOT NULL,
    T_PEOPLE_ID bigint NOT NULL references T_PEOPLE(ID) ON DELETE CASCADE,
    ADDR_TYPE VARCHAR(5) NOT NULL,
    ADDR_INFO VARCHAR(300),
    primary key (ID)
);

CREATE TABLE T_TYPES (
    ID_TYPE VARCHAR(5) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    SORT_DESC VARCHAR(30) NOT NULL,
    primary key (ID_TYPE)
);

CREATE TABLE T_SALARY (
    ID bigint NOT NULL,
    T_PEOPLE_ID bigint NOT NULL references T_PEOPLE(ID) ON DELETE CASCADE,
    YEAR INT NOT NULL,
    MONTH INT NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL,
    primary key (ID)
);

